### ISSUE TITLE
UI Bugs & Changes

### ISSUE THREAD

**Issue by 0xdeval** [zkBob/zkbob-ui#105]
## What to do?

Gathered UI bugs/changes that we need to support for the app:

- [x] UI copies: https://www.notion.so/blockscout/UI-bags-51b3fe6e3b7b4dedb5f869a68d9507a4
- [x] Support fee displaying: https://www.notion.so/blockscout/Add-fees-displaying-in-the-history-tab-c1712ce595d744238c6a8beb990ba3bf?pvs=4
- [x] Remove frames for the seeded phrase (users complained on this UI, they don't understand that it's not button): https://github.com/zkBob/zkbob-ui/issues/103
- [x] Disable the dropdown menu when the account is loading: https://github.com/zkBob/zkbob-ui/issues/102
- [x] Add skeleton for limits and balance: https://github.com/zkBob/zkbob-ui/issues/96
